# Brazilian Portuguese message translation file for plpython
# Copyright (C) 2009 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
# Euler Taveira de Oliveira <euler@timbira.com>, 2009-2015.
#
msgid ""
msgstr ""
"Project-Id-Version: PostgreSQL 9.1\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2015-05-17 16:09-0300\n"
"PO-Revision-Date: 2009-05-10 01:15-0300\n"
"Last-Translator: Euler Taveira de Oliveira <euler@timbira.com>\n"
"Language-Team: Brazilian Portuguese <pgbr-dev@listas.postgresql.org.br>\n"
"Language: pt_BR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n>1);\n"

#: plpython.c:482
#, c-format
msgid "PL/Python function \"%s\""
msgstr "função PL/Python \"%s\""

#: plpython.c:489
msgid "PL/Python anonymous code block"
msgstr "bloco de código PL/Python anônimo"

#: plpython.c:496
msgid "while modifying trigger row"
msgstr "ao modificar registro de gatilho"

#: plpython.c:503
msgid "while creating return value"
msgstr "ao criar valor de retorno"

#: plpython.c:720 plpython.c:746
msgid "unexpected return value from trigger procedure"
msgstr "função de gatilho retornou valor inesperado"

#: plpython.c:721
msgid "Expected None or a string."
msgstr "None ou uma cadeia de caracteres era esperado."

#: plpython.c:736
msgid ""
"PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr ""
"função de gatilho PL/Python retornou \"MODIFY\" em um gatilho DELETE -- "
"ignorado"

#: plpython.c:747
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Era esperado None, \"OK\", \"SKIP\" ou \"MODIFY\"."

#: plpython.c:797
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] removido, não pode modificar registro"

#: plpython.c:801
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] não é um dicionário"

#: plpython.c:825
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr ""
"chave do dicionário TD[\"new\"] na posição %d não é uma cadeia de caracteres"

#: plpython.c:831
#, c-format
msgid ""
"key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering "
"row"
msgstr ""
"chave \"%s\" encontrada em TD[\"new\"] não existe como uma coluna no "
"registro do gatilho"

#: plpython.c:926
msgid "could not create new dictionary while building trigger arguments"
msgstr "não pode criar novo dicionário ao construir argumentos do gatilho"

#: plpython.c:1133
msgid "unsupported set function return mode"
msgstr "modo de retorno da função que retorna conjunto não é suportado"

#: plpython.c:1134
msgid ""
"PL/Python set-returning functions only support returning one value per call."
msgstr ""
"funções PL/Python que retornam conjunto só suportam retornar um valor por "
"chamada."

#: plpython.c:1146
msgid "returned object cannot be iterated"
msgstr "objeto retornado não pode ser iterado"

#: plpython.c:1147
msgid "PL/Python set-returning functions must return an iterable object."
msgstr ""
"funções PL/Python que retornam conjunto devem retornar um objeto iterável."

#: plpython.c:1172
msgid "error fetching next item from iterator"
msgstr "erro ao buscar próximo item do iterador"

#: plpython.c:1207
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "função PL/Python com tipo de retorno \"void\" não retornou None"

#: plpython.c:1287
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr "forçado a abortar subtransação que não foi concluída"

#: plpython.c:1403
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "PyList_SetItem() falhou ao definir argumentos"

#: plpython.c:1407
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "PyDict_SetItemString() falhou ao definir argumentos"

#: plpython.c:1419
msgid ""
"function returning record called in context that cannot accept type record"
msgstr ""
"função que retorna record foi chamada em um contexto que não pode aceitar "
"tipo record"

#: plpython.c:1667
msgid "trigger functions can only be called as triggers"
msgstr "funções de gatilho só podem ser chamadas como gatilhos"

#: plpython.c:1672 plpython.c:2145
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "funções PL/Python não podem retornar tipo %s"

#: plpython.c:1754
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "funções PL/Python não podem aceitar tipo %s"

#: plpython.c:1850
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "não pôde compilar função PL/Python \"%s\""

#: plpython.c:1853
msgid "could not compile anonymous PL/Python code block"
msgstr "não pôde compilar bloco de código PL/Python anônimo"

#: plpython.c:2147
msgid "PL/Python does not support conversion to arrays of row types."
msgstr "PL/Python não suporta conversão para matrizes de tipos row."

#: plpython.c:2356
msgid "cannot convert multidimensional array to Python list"
msgstr "não pode converter matriz multidimensional para lista Python"

#: plpython.c:2357
msgid "PL/Python only supports one-dimensional arrays."
msgstr "PL/Python só suporta matrizes unidimensionais."

#: plpython.c:2363
msgid "could not create new list"
msgstr "não pôde criar nova lista"

#: plpython.c:2398
msgid "could not create new dictionary"
msgstr "não pôde criar novo dicionário"

#: plpython.c:2495
msgid "could not create bytes representation of Python object"
msgstr "não pôde criar representação de bytes de um objeto Python"

#: plpython.c:2587
msgid "could not create string representation of Python object"
msgstr ""
"não pôde criar representação de cadeia de caracteres de um objeto Python"

#: plpython.c:2598
msgid ""
"could not convert Python object into cstring: Python string representation "
"appears to contain null bytes"
msgstr ""
"não pôde converter objeto Python em cstring: representação de cadeia de "
"caracteres Python parece conter bytes nulos"

#: plpython.c:2632
msgid ""
"return value of function with array return type is not a Python sequence"
msgstr ""
"valor de retorno da função do tipo matriz retorna tipo que não é uma "
"sequência Python"

#: plpython.c:2732
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "chave \"%s\" não foi encontrada no mapeamento"

#: plpython.c:2733
msgid ""
"To return null in a column, add the value None to the mapping with the key "
"named after the column."
msgstr ""
"Para retornar nulo em uma coluna, adicionar o valor None no mapeamento cuja "
"chave é o nome da coluna."

#: plpython.c:2781
msgid "length of returned sequence did not match number of columns in row"
msgstr ""
"tamanho da sequência retornada não combina com número de colunas no registro"

#: plpython.c:2889
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "atributo \"%s\" não existe no objeto Python"

#: plpython.c:2890
msgid ""
"To return null in a column, let the returned object have an attribute named "
"after column with value None."
msgstr ""
"Para retornar nulo na coluna, deixe o objeto retornado ter um atributo cuja "
"chave é o nome do coluna e o valor é None."

#: plpython.c:3209
msgid "plan.status takes no arguments"
msgstr "plan.status não contém argumentos"

#: plpython.c:3333
msgid "second argument of plpy.prepare must be a sequence"
msgstr "segundo argumento de plpy.prepare deve ser uma sequência"

#: plpython.c:3383
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr ""
"plpy.prepare: nome do tipo na posição %d não é uma cadeia de caracteres"

#: plpython.c:3415
msgid "plpy.prepare does not support composite types"
msgstr "plpy.prepare não suporta tipos compostos"

#: plpython.c:3505
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute espera uma consulta ou um plano"

#: plpython.c:3524
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute recebe uma sequência como segundo argumento"

#: plpython.c:3540
msgid "could not execute plan"
msgstr "não pôde executar plano"

#: plpython.c:3543
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Sequência esperada de %d argumento, recebeu %d: %s"
msgstr[1] "Sequência esperada de %d argumentos, recebeu %d: %s"

#: plpython.c:3685
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "SPI_execute_plan falhou: %s"

#: plpython.c:3764
#, c-format
msgid "SPI_execute failed: %s"
msgstr "SPI_execute falhou: %s"

#: plpython.c:3819
msgid "unrecognized error in PLy_spi_execute_fetch_result"
msgstr "erro desconhecido em PLy_spi_execute_fetch_result"

#: plpython.c:3881
msgid "this subtransaction has already been entered"
msgstr "essa subtransação já foi iniciada"

#: plpython.c:3887 plpython.c:3939
msgid "this subtransaction has already been exited"
msgstr "essa subtransação já foi concluída"

#: plpython.c:3933
msgid "this subtransaction has not been entered"
msgstr "essa subtransação não foi iniciada"

#: plpython.c:3945
msgid "there is no subtransaction to exit from"
msgstr "não há uma subtransação a ser concluída"

#: plpython.c:4004 plpython.c:4008
msgid "could not generate SPI exceptions"
msgstr "não pôde gerar exceções da SPI"

#: plpython.c:4033
msgid "could not add the spiexceptions module"
msgstr "não pôde adicionar o módulo spiexceptions"

#: plpython.c:4053
msgid "could not create the base SPI exceptions"
msgstr "não pôde criar as exceções base da SPI"

#: plpython.c:4121
msgid "Python major version mismatch in session"
msgstr "versão do Python não corresponde na sessão"

#: plpython.c:4122
#, c-format
msgid ""
"This session has previously used Python major version %d, and it is now "
"attempting to use Python major version %d."
msgstr ""
"Esta sessão utilizou Python versão %d, e agora está tentando utilizar Python "
"versão %d."

#: plpython.c:4124
msgid "Start a new session to use a different Python major version."
msgstr "Inicie uma nova sessão para utilizar uma versão diferente do Python."

#: plpython.c:4139
msgid "untrapped error in initialization"
msgstr "erro não interceptado na inicialização"

#: plpython.c:4160
msgid "could not import \"__main__\" module"
msgstr "não pôde importar módulo \"__main__\""

#: plpython.c:4165
msgid "could not create globals"
msgstr "não pôde criar globais"

#: plpython.c:4169
msgid "could not initialize globals"
msgstr "não pôde inicializar globais"

#: plpython.c:4207 plpython.c:4210
msgid "could not import \"plpy\" module"
msgstr "não pôde importar módulo \"plpy\""

#: plpython.c:4277
msgid "could not unpack arguments in plpy.elog"
msgstr "não pode desempacotar argumentos em plpy.elog"

#: plpython.c:4285
msgid "could not parse error message in plpy.elog"
msgstr "não pode analisar mensagem de erro em plpy.elog"

#: plpython.c:4309 plpython.c:4543 plpython.c:4544
#, c-format
msgid "%s"
msgstr "%s"

#: plpython.c:4895
msgid "could not convert Python Unicode object to bytes"
msgstr "não pôde converter objeto Unicode Python para bytes"

#: plpython.c:4900
msgid "could not extract bytes from encoded string"
msgstr "não pôde extrair bytes de cadeia de caracteres codificada"
